import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowRight, ChevronRight, ExternalLink } from "lucide-react";
import Footer from "../../../components/Footer";
import { caseStudies, publishedCaseStudies } from "../../../lib/editorial";
import { siteConfig } from "../../../lib/seo";

export function generateStaticParams() { return publishedCaseStudies.map(({ slug }) => ({ slug })); }
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const { slug } = await params; const item = publishedCaseStudies.find((entry) => entry.slug === slug); return item ? { title: item.title, description: item.description, alternates: { canonical: `/work/${slug}` }, openGraph: { title: item.title, description: item.description, images: [item.image] } } : {}; }

export default async function CaseStudyPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params; const item = caseStudies.find((entry) => entry.slug === slug); if (!item || item.status !== "published") notFound(); const url = `${siteConfig.url}/work/${slug}`;
  const schema = { "@context": "https://schema.org", "@graph": [{ "@type": "CreativeWork", "@id": `${url}#case-study`, name: item.title, description: item.description, datePublished: item.published, image: `${siteConfig.url}${item.image}`, creator: { "@id": `${siteConfig.url}/#organization` }, about: item.services.map(({ label }) => label), url }, { "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "Home", item: siteConfig.url }, { "@type": "ListItem", position: 2, name: "Work", item: `${siteConfig.url}/work` }, { "@type": "ListItem", position: 3, name: item.client, item: url }] }] };
  return <main className="min-h-screen bg-black text-white"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema).replace(/</g, "\\u003c") }} />
    <header className="px-6 pb-16 pt-36 md:pt-44"><div className="mx-auto max-w-6xl"><nav aria-label="Breadcrumb" className="mb-9 flex items-center gap-2 text-sm text-gray-500"><Link href="/">Home</Link><ChevronRight className="h-4 w-4"/><Link href="/work">Work</Link><ChevronRight className="h-4 w-4"/><span>{item.client}</span></nav><p className="font-mono text-sm uppercase tracking-[.2em] text-emerald-300">{item.category}</p><h1 className="mt-5 max-w-5xl text-5xl font-bold tracking-tight md:text-7xl">{item.title}</h1><p className="mt-7 max-w-3xl text-xl leading-relaxed text-gray-300">{item.description}</p></div></header>
    <div className="px-6"><div className="relative mx-auto aspect-[16/9] max-w-6xl overflow-hidden rounded-3xl border border-white/10"><Image src={item.image} alt={`${item.client} project interface`} fill priority sizes="(max-width: 1200px) 100vw, 1200px" className="object-cover object-top" /></div></div>
    <section className="px-6 py-20"><div className="mx-auto grid max-w-6xl gap-12 lg:grid-cols-[1fr_.7fr]"><div className="space-y-12"><div><h2 className="text-3xl font-bold">The challenge</h2><p className="mt-5 text-lg leading-8 text-gray-300">{item.challenge}</p></div><div><h2 className="text-3xl font-bold">What Kindforth built</h2><p className="mt-5 text-lg leading-8 text-gray-300">{item.solution}</p></div><div><h2 className="text-3xl font-bold">Delivery process</h2><ol className="mt-6 grid gap-3">{item.process.map((step, index) => <li key={step} className="rounded-2xl border border-white/10 bg-white/[.03] p-5 text-gray-300"><span className="mr-3 font-mono text-blue-400">{String(index + 1).padStart(2, "0")}</span>{step}</li>)}</ol></div></div>
      <aside><div className="sticky top-28 rounded-3xl border border-white/10 bg-white/[.04] p-7"><p className="font-mono text-xs uppercase tracking-widest text-blue-300">Verified outcomes</p><div className="mt-6 grid grid-cols-2 gap-4">{item.outcomes.map((outcome) => <div key={outcome.label}><p className="text-2xl font-bold">{outcome.value}</p><p className="mt-1 text-xs text-gray-500">{outcome.label}</p></div>)}</div><div className="mt-8 border-t border-white/10 pt-6">{item.services.map((service) => <Link key={service.href} href={service.href} className="mb-3 flex items-center justify-between text-sm text-gray-300 hover:text-white">{service.label}<ArrowRight className="h-4 w-4"/></Link>)}</div>{item.website && <a href={item.website} target="_blank" rel="noreferrer" className="mt-5 inline-flex items-center gap-2 text-sm font-semibold text-blue-300">Visit live project <ExternalLink className="h-4 w-4"/></a>}</div></aside>
    </div></section>
    {item.testimonial && <section className="border-y border-white/10 bg-white/[.03] px-6 py-20"><blockquote className="mx-auto max-w-4xl text-center"><p className="text-2xl font-medium leading-relaxed md:text-4xl">“{item.testimonial.quote}”</p><footer className="mt-7 text-gray-400">{item.testimonial.attribution}</footer></blockquote></section>}
    <section className="px-6 py-20 text-center"><h2 className="text-4xl font-bold">Have a similar challenge?</h2><Link href="/contact" className="mt-7 inline-flex items-center gap-2 rounded-full bg-blue-600 px-7 py-4 font-bold">Start a project <ArrowRight className="h-5 w-5"/></Link></section><Footer /></main>;
}
