export type ContentSection = { heading: string; paragraphs: string[]; bullets?: string[] };

export type Insight = {
  slug: string; title: string; description: string; category: string; author: "Rajindra Ratnayake" | "Nipun Nirmal";
  reviewer: "Rajindra Ratnayake" | "Nipun Nirmal"; published: string; updated: string; readingTime: string;
  status: "published" | "draft"; relatedService: string; relatedServiceLabel: string; sections: ContentSection[];
};

export const insights: Insight[] = [
  {
    slug: "seo-aeo-geo-sri-lankan-smes", title: "SEO, AEO and GEO for Sri Lankan SMEs", category: "Search growth",
    description: "A practical founder guide to earning visibility in Google Search, AI answers, and generative search without chasing short-lived hacks.",
    author: "Rajindra Ratnayake", reviewer: "Nipun Nirmal", published: "2026-08-30", updated: "2026-08-30", readingTime: "9 min read", status: "published",
    relatedService: "/services/seo", relatedServiceLabel: "SEO and organic growth",
    sections: [
      { heading: "The short answer", paragraphs: ["Sri Lankan SMEs do not need three disconnected strategies. SEO makes a business crawlable, relevant, and trusted. AEO makes its explanations easy to retrieve and quote. GEO strengthens the evidence and entity signals that generative systems use when choosing sources. The durable work overlaps: useful pages, first-hand evidence, clear authorship, consistent business information, and reputable mentions."] },
      { heading: "Start with commercial search demand", paragraphs: ["Begin with the problems customers already search for, not a list of every phrase a keyword tool can generate. A useful service page should explain who the service is for, what is delivered, how decisions are made, what evidence supports the claims, and how a buyer can take the next step."], bullets: ["Map one primary intent to each commercial page", "Answer the main buying question near the beginning", "Support the answer with process, proof, FAQs, and related work", "Measure enquiries rather than treating traffic as the final result"] },
      { heading: "Make expertise attributable", paragraphs: ["Anonymous generic advice is easy to reproduce. Founder-reviewed material based on delivery experience is harder to replace and easier to trust. Name the author and reviewer, show their relevant expertise, use original screenshots or diagrams, and state when the information was updated."], bullets: ["Connect author pages to the company and relevant projects", "Separate observed results from opinions and forecasts", "Cite primary sources for changing technical claims", "Correct outdated material instead of producing near-duplicate pages"] },
      { heading: "Prepare facts for answer engines", paragraphs: ["Use descriptive headings followed by a concise factual answer, then provide the nuance and evidence. This serves hurried buyers, screen readers, search engines, and AI retrieval systems without writing robotic fragments."], bullets: ["Keep the company name, services, founders, phone, and location consistent", "Use structured data only when it matches visible content", "Allow legitimate search crawlers to access public pages", "Build specific pages that other sites have a reason to cite"] },
      { heading: "A realistic 90-day programme", paragraphs: ["The first month should establish measurement, fix indexing, and improve the service page with the clearest demand. The second should publish evidence-rich case studies and one expert guide. The third should extend the topic cluster and earn relevant client, partner, directory, or editorial links. Rankings can move unevenly; qualified visibility and enquiries are the more useful trend."], bullets: ["Weeks 1–2: measurement, entity consistency, and indexation", "Weeks 3–6: service-page depth and case-study proof", "Weeks 7–12: expert publishing, reviews, citations, and links"] },
    ],
  },
  {
    slug: "local-seo-sri-lankan-service-businesses", title: "Local SEO for Sri Lankan Service Businesses: A Practical Checklist", category: "Local search",
    description: "A field checklist for service-area companies that want qualified Sri Lankan visibility without fake addresses or doorway pages.",
    author: "Nipun Nirmal", reviewer: "Rajindra Ratnayake", published: "2026-09-14", updated: "2026-09-14", readingTime: "8 min read", status: "draft",
    relatedService: "/services/seo", relatedServiceLabel: "Local SEO services",
    sections: [
      { heading: "Use a truthful local footprint", paragraphs: ["A service-area business should use a real operating address for verification, hide it when customers are not served there, and list only areas the team genuinely serves. Virtual-office locations and city pages with no distinct value create risk rather than durable visibility."] },
      { heading: "Complete the business entity", paragraphs: ["Keep the business name, primary category, services, phone, hours, website, founders, and description consistent across the website, Google Business Profile, social profiles, and reputable directories."], bullets: ["Choose the category that best represents the core business", "Add real project and team images", "Use UTM parameters on the profile website link", "Keep holiday and special hours current"] },
      { heading: "Build local evidence", paragraphs: ["Local relevance comes from real relationships and delivery. Publish Sri Lankan case studies, request honest client reviews, earn links from clients and partners, and participate in relevant industry or community activity."], bullets: ["Never buy or incentivize reviews", "Reply to reviews with useful, non-scripted context", "Ask clients to mention the service they actually received", "Link each case study to the relevant service page"] },
      { heading: "Measure outcomes", paragraphs: ["Track profile calls, website visits, forms, WhatsApp conversations, and qualified proposals. Search rankings alone cannot show whether local visibility is producing suitable work."] },
    ],
  },
  {
    slug: "custom-software-vs-off-the-shelf-sri-lanka", title: "Custom Software vs Off-the-Shelf Software for Sri Lankan SMEs", category: "Software decisions",
    description: "A decision framework for choosing between subscription software, integrations, automation, and a purpose-built system.",
    author: "Rajindra Ratnayake", reviewer: "Nipun Nirmal", published: "2026-09-28", updated: "2026-09-28", readingTime: "10 min read", status: "draft",
    relatedService: "/services/custom-software-development", relatedServiceLabel: "Custom software development",
    sections: [
      { heading: "Choose the simplest system that fits", paragraphs: ["Custom software is not automatically better. A mature off-the-shelf product is usually the right first choice when the workflow is standard, implementation speed matters, and the subscription cost is lower than owning a product."] },
      { heading: "When custom software becomes sensible", paragraphs: ["A tailored system becomes valuable when a workflow creates competitive advantage, repeated compromises cost real time or revenue, integrations are essential, or existing tools cannot meet security and control requirements."], bullets: ["Quantify hours, errors, delays, and licence costs", "Identify the smallest differentiating workflow", "Test risky assumptions before committing to a full build", "Include maintenance and adoption in the business case"] },
      { heading: "Consider a connected middle path", paragraphs: ["Many SMEs do not need a full replacement. An integration, focused internal application, or automation layer can preserve useful existing tools while removing the most expensive gaps."] },
      { heading: "Evaluate total cost and ownership", paragraphs: ["Compare five-year subscription and customization costs with discovery, development, hosting, maintenance, training, and change management. Also decide who owns the code, data, infrastructure, and product decisions."] },
    ],
  },
  {
    slug: "where-ai-automation-saves-time", title: "Where AI Automation Actually Saves Time in a Sri Lankan Business", category: "AI automation",
    description: "A practical method for finding automation opportunities that save measurable time without removing necessary human judgement.",
    author: "Rajindra Ratnayake", reviewer: "Nipun Nirmal", published: "2026-10-12", updated: "2026-10-12", readingTime: "9 min read", status: "draft",
    relatedService: "/services/business-automation", relatedServiceLabel: "Business automation",
    sections: [
      { heading: "Look for repetition before novelty", paragraphs: ["The best first automation is rarely the most dramatic AI demonstration. It is a frequent, rules-heavy process with measurable handling time, a stable input, and a clear human owner."] },
      { heading: "Strong first candidates", paragraphs: ["Document intake, enquiry classification, appointment reminders, recurring reporting, data reconciliation, and internal knowledge search often provide clearer value than an unconstrained autonomous agent."], bullets: ["Count monthly volume and minutes per task", "Measure error and rework rates", "Define exceptions and escalation paths", "Keep an audit trail for important actions"] },
      { heading: "Where humans should stay in control", paragraphs: ["Approvals involving money, safety, employment, sensitive customer decisions, or ambiguous context should retain meaningful human review. The system should explain what it used and make exceptions visible."] },
      { heading: "Prove value in a narrow pilot", paragraphs: ["Choose one process, establish a baseline, run a limited pilot, and compare time, quality, adoption, and operating cost. Expand only after the evidence is strong enough."] },
    ],
  },
];

export type CaseStudy = {
  slug: string; client: string; title: string; description: string; category: string; image: string; website?: string;
  published: string; status: "published" | "draft"; services: { label: string; href: string }[]; challenge: string; solution: string;
  outcomes: { label: string; value: string }[]; process: string[]; testimonial?: { quote: string; attribution: string };
};

export const caseStudies: CaseStudy[] = [
  { slug: "yellow-flag-podcast", client: "Yellow Flag Podcast", title: "An Owned Audience Experience for Yellow Flag Podcast", description: "A fast podcast website and interactive games that give fans more ways to engage between YouTube uploads.", category: "Media & audience engagement", image: "/yellowflag.png", website: "https://yellowflagpodcast.com", published: "2026-08-30", status: "published", services: [{ label: "Web application development", href: "/services/web-application-development" }, { label: "Custom software", href: "/services/custom-software-development" }], challenge: "The audience primarily lived inside YouTube's feed. After an episode ended, the creators had limited ways to bring viewers into an experience they owned or give fans a reason to return between uploads.", solution: "Kindforth created a dedicated website that brings episodes together and added interactive games designed around fan participation. The platform gives Yellow Flag room to expand its audience experience beyond a single social channel.", outcomes: [{ label: "Audience experience", value: "Website + games" }, { label: "Delivery", value: "Live" }], process: ["Mapped the viewer journey from YouTube to an owned destination", "Designed the site and games around the podcast's identity", "Built a responsive Next.js experience", "Tested, launched, and refined the live platform"], testimonial: { quote: "Kindforth went above and beyond what we expected. They built our website and interactive games that give our audience more ways to engage with Yellow Flag. We highly recommend them and will definitely work with Kindforth again.", attribution: "Lakindu Siriwadana & Kasun Udayangana, Content Creators, Yellow Flag Podcast" } },
  { slug: "gomez-hospital", client: "Gomez Hospital", title: "A Faster Digital Booking Experience for Gomez Hospital", description: "A healthcare booking platform designed to reduce manual intake friction and make appointment availability easier to manage.", category: "Healthcare automation", image: "/gomez-site22.png", published: "2026-08-30", status: "published", services: [{ label: "Business automation", href: "/services/business-automation" }, { label: "Web application development", href: "/services/web-application-development" }], challenge: "Manual booking errors contributed to lost revenue, while patient intake took approximately 15 minutes per person. The hospital needed a clearer, more dependable path from appointment discovery to confirmation.", solution: "Kindforth designed and built a digital booking experience with structured availability and operational workflows, reducing repetitive handling while preserving staff control over appointments.", outcomes: [{ label: "Booking speed", value: "+40%" }, { label: "Platform uptime", value: "99.9%" }], process: ["Documented the existing booking and intake workflow", "Defined availability, validation, and exception rules", "Built the patient and administration journeys", "Deployed monitoring and iterated with operational feedback"] },
  { slug: "call-me-taxi", client: "Call Me Taxi", title: "A 24/7 Online Booking Flow for Call Me Taxi", description: "An always-on booking front end with live dispatch notifications for a Sri Lankan taxi operation.", category: "Mobility & booking", image: "/callmetaxi.png", website: "https://callmetaxi.lk", published: "2026-10-26", status: "draft", services: [{ label: "Web application development", href: "/services/web-application-development" }], challenge: "Rides depended on phone calls, creating missed-booking risk at night and during peak periods.", solution: "Kindforth built an online booking flow and dispatch notifications so customers can submit rides at any hour and the operation can respond from one structured process.", outcomes: [{ label: "Availability", value: "24/7" }, { label: "Dispatch", value: "Instant alerts" }], process: ["Mapped customer and dispatcher needs", "Designed a mobile-first booking path", "Integrated real-time notifications", "Tested the production workflow"] },
  { slug: "sathimath-viweka-senasuna", client: "Sathimath Viweka Senasuna", title: "A Bilingual Digital Sanctuary and Booking System", description: "A calm bilingual website and retreat-booking experience for a Sri Lankan meditation centre.", category: "Community & booking", image: "/asapuwa.jpg", website: "https://sathimathvivekasenasuna.lk", published: "2026-11-09", status: "draft", services: [{ label: "Web application development", href: "/services/web-application-development" }], challenge: "Visitors had difficulty finding reliable location information and arranging meditation visits because the centre had no complete digital presence.", solution: "Kindforth created a bilingual English and Sinhala experience with clear information and a structured booking flow that reflects the centre's calm identity.", outcomes: [{ label: "Languages", value: "English + Sinhala" }, { label: "Bookings", value: "Automated" }], process: ["Organized bilingual content and visitor needs", "Designed a calm accessible interface", "Built the booking experience", "Prepared the platform for ongoing updates"] },
];

export const publishedInsights = insights.filter((item) => item.status === "published");
export const publishedCaseStudies = caseStudies.filter((item) => item.status === "published");
